### ISSUE TITLE
can not use 'local-addr' option to specify Local source address for outgoing connections

### ISSUE THREAD

**Issue by Baoxd123** [gakiwate/sentinel-zgrab2#7]
'config.go' has the "localAddr          *net.TCPAddr", but 'local-addr' option was not realized to use.

**Comment by gakiwate** [comment]
@Baoxd123 Thanks for the PR. Can you add a short description of when you would use local addr in your PR?

**Comment by Baoxd123** [comment]
> @Baoxd123 Thanks for the PR. Can you add a short description of when you would use local addr in your PR?

Thanks for your reply. To avoid the website server blocking the user's IP address when using zgrab2 to scan the same website multiple times, the user will need to use multiple source IP addresses(local addr) for load balancing to avoid the same src ip being blocked by the server and causing subsequent connections to be rejected.
